# Text Style Transfer Config
defaults:
  - base_tst
  - _self_
# Data
dataset: "???"
dataset_seed: null
direction: "???"
# Reward
# style_classifier: "/home/yschoi/rl-prompt-filter/examples/text-style-transfer/style_classifiers/yelp-bert-base-uncased-train"
style_classifier: "/root/rl-prompt-filter/examples/text-style-transfer/style_classifiers/yelp-bert-base-uncased-train/"
style_tokenizer: "bert-base-uncased"
lower_outputs: true
control_output_length: true
num_repeats: 8 # prompt_train_batch_size / train_batch_size
pad_token: "<pad>"
# Single Prompt Model
prompt_length: 5
prompt_train_batch_size: 16
prompt_infer_batch_size: 16
# LM Adaptor Model
logit_bias: false
# SQL Module
reward_shaping_old_min: 0
reward_shaping_old_max: 1
reward_shaping_new_min: 0 #-20
reward_shaping_new_max: 1 # 80
top_k: 50
# Trainer
train_batch_size: 2
max_train_steps: 15000
train_shuffle: false
eval_batch_size: 16
eval_steps: 50
save_steps: 1000
learning_rate: 5e-5
random_seed: null
# save_dir: /ext_hdd/ys
save_dir: /output
num_exp: 1000
